<script setup lang="ts">
definePageMeta({
  title: "theerapakg-moe-app: honakana event statistics",
  name: "HonaKana Stats!",
});

const plotCharts = async () => {
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore
  const Plotly = await import("plotly.js-dist");

  const colorMode = useColorMode();
  console.log(colorMode.value);

  Plotly.newPlot(
    "1ece9e8b-b3de-4c21-a2ca-79603884e11e",
    [
      {
        alignmentgroup: "True",
        cliponaxis: false,
        hovertemplate:
          "Type=Fill\u003cbr\u003eHours=%{x}\u003cbr\u003ePlayer=%{y}\u003cextra\u003e\u003c\u002fextra\u003e",
        legendgroup: "Fill",
        marker: { color: "deepskyblue", pattern: { shape: "" } },
        name: "Fill",
        offsetgroup: "Fill",
        orientation: "h",
        showlegend: true,
        textangle: 0,
        textposition: "inside",
        texttemplate: "%{x}",
        x: [
          3, 69, 23, 13, 1, 4, 2, 1, 23, 2, 29, 1, 1, 5, 3, 5, 47, 6, 9, 5, 1,
          19, 2, 3, 2, 1, 1, 3, 41, 2, 3, 1, 3, 3, 3, 11, 4, 3, 3, 2, 1, 2, 2,
          3, 2, 1, 4, 1,
        ],
        xaxis: "x",
        y: [
          "Levi",
          "Ninmay",
          "TheerapakG",
          "Ane",
          "chinatsu",
          "Ayu",
          "Zephyr",
          "Zephyr Alt",
          "sagi",
          "Berryy",
          "Cycada",
          "koomee",
          "Marina",
          "\u535a\u9e97\u970a\u5922 (Alls)",
          "jayy",
          "sabre",
          "ninmay alt",
          "alex",
          "CQ",
          "CQ (alt)",
          "Waffle",
          "yukari",
          "slay",
          "Carbage",
          "Linkle",
          "clemeycat",
          "orange",
          "lizzie",
          "Yuu",
          "loom",
          "tofeliiiiiiz",
          "Yozora",
          "Kurumi!!",
          "roxas",
          "luna",
          "Suzu",
          "bunch",
          "An!",
          "Kenny (baryons)",
          "DaraDara",
          "Fuego",
          "Sagi alt",
          "shua \u2661",
          "PUBGE",
          "rav",
          "Tiny",
          "Tai \u2727 \u002f\u002f\u002f",
          "woaichixigua",
        ],
        yaxis: "y",
        type: "bar",
      },
      {
        alignmentgroup: "True",
        cliponaxis: false,
        hovertemplate:
          "Type=Filled Halfway\u003cbr\u003eHours=%{x}\u003cbr\u003ePlayer=%{y}\u003cextra\u003e\u003c\u002fextra\u003e",
        legendgroup: "Filled Halfway",
        marker: { color: "lawngreen", pattern: { shape: "" } },
        name: "Filled Halfway",
        offsetgroup: "Filled Halfway",
        orientation: "h",
        showlegend: true,
        textangle: 0,
        textposition: "inside",
        texttemplate: "%{x}",
        x: [
          0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0,
        ],
        xaxis: "x",
        y: [
          "Levi",
          "Ninmay",
          "TheerapakG",
          "Ane",
          "chinatsu",
          "Ayu",
          "Zephyr",
          "Zephyr Alt",
          "sagi",
          "Berryy",
          "Cycada",
          "koomee",
          "Marina",
          "\u535a\u9e97\u970a\u5922 (Alls)",
          "jayy",
          "sabre",
          "ninmay alt",
          "alex",
          "CQ",
          "CQ (alt)",
          "Waffle",
          "yukari",
          "slay",
          "Carbage",
          "Linkle",
          "clemeycat",
          "orange",
          "lizzie",
          "Yuu",
          "loom",
          "tofeliiiiiiz",
          "Yozora",
          "Kurumi!!",
          "roxas",
          "luna",
          "Suzu",
          "bunch",
          "An!",
          "Kenny (baryons)",
          "DaraDara",
          "Fuego",
          "Sagi alt",
          "shua \u2661",
          "PUBGE",
          "rav",
          "Tiny",
          "Tai \u2727 \u002f\u002f\u002f",
          "woaichixigua",
        ],
        yaxis: "y",
        type: "bar",
      },
      {
        alignmentgroup: "True",
        cliponaxis: false,
        hovertemplate:
          "Type=Fill Cancelled by Katsu\u003cbr\u003eHours=%{x}\u003cbr\u003ePlayer=%{y}\u003cextra\u003e\u003c\u002fextra\u003e",
        legendgroup: "Fill Cancelled by Katsu",
        marker: { color: "darkorange", pattern: { shape: "" } },
        name: "Fill Cancelled by Katsu",
        offsetgroup: "Fill Cancelled",
        orientation: "h",
        showlegend: true,
        textangle: 0,
        textposition: "inside",
        texttemplate: "%{x}",
        x: [
          0, 24, 8, 4, 0, 0, 0, 0, 6, 0, 1, 0, 2, 3, 1, 0, 21, 0, 4, 4, 0, 5, 0,
          0, 0, 0, 0, 2, 3, 0, 2, 0, 0, 0, 2, 6, 0, 1, 1, 2, 0, 0, 0, 0, 0, 0,
          0, 0,
        ],
        xaxis: "x",
        y: [
          "Levi",
          "Ninmay",
          "TheerapakG",
          "Ane",
          "chinatsu",
          "Ayu",
          "Zephyr",
          "Zephyr Alt",
          "sagi",
          "Berryy",
          "Cycada",
          "koomee",
          "Marina",
          "\u535a\u9e97\u970a\u5922 (Alls)",
          "jayy",
          "sabre",
          "ninmay alt",
          "alex",
          "CQ",
          "CQ (alt)",
          "Waffle",
          "yukari",
          "slay",
          "Carbage",
          "Linkle",
          "clemeycat",
          "orange",
          "lizzie",
          "Yuu",
          "loom",
          "tofeliiiiiiz",
          "Yozora",
          "Kurumi!!",
          "roxas",
          "luna",
          "Suzu",
          "bunch",
          "An!",
          "Kenny (baryons)",
          "DaraDara",
          "Fuego",
          "Sagi alt",
          "shua \u2661",
          "PUBGE",
          "rav",
          "Tiny",
          "Tai \u2727 \u002f\u002f\u002f",
          "woaichixigua",
        ],
        yaxis: "y",
        type: "bar",
      },
    ],
    {
      barmode: "relative",
      font: {
        family: "YurukaStd",
        color: colorMode.value === "dark" ? "white" : "black",
      },
      height: 1600,
      legend: { title: { text: "Type" }, tracegroupgap: 0 },
      paper_bgcolor: colorMode.value === "dark" ? "black" : "white",
      plot_bgcolor: colorMode.value === "dark" ? "black" : "white",
      template: {
        layout: {
          paper_bgcolor: colorMode.value === "dark" ? "black" : "white",
          plot_bgcolor: "#E5ECF6",
          title: { x: 0.05 },
          xaxis: {
            automargin: true,
            gridcolor: colorMode.value === "dark" ? "black" : "white",
            linecolor: colorMode.value === "dark" ? "black" : "white",
            ticks: "",
            title: { standoff: 15 },
            zerolinecolor: colorMode.value === "dark" ? "black" : "white",
            zerolinewidth: 2,
          },
          yaxis: {
            automargin: true,
            gridcolor: colorMode.value === "dark" ? "black" : "white",
            linecolor: colorMode.value === "dark" ? "black" : "white",
            ticks: "",
            title: { standoff: 15 },
            zerolinecolor: colorMode.value === "dark" ? "black" : "white",
            zerolinewidth: 2,
          },
        },
      },
      title: {
        font: { size: 48 },
        text: "Fill",
        x: 0.5,
        xanchor: "center",
        y: 0.96,
        yanchor: "middle",
      },
      xaxis: {
        anchor: "y",
        domain: [0.0, 1.0],
        gridcolor: "silver",
        gridwidth: 1,
        showgrid: true,
        title: { text: "Hours" },
        zeroline: true,
        zerolinecolor: colorMode.value === "dark" ? "white" : "black",
        zerolinewidth: 2,
      },
      yaxis: {
        anchor: "x",
        categoryorder: "total ascending",
        domain: [0.0, 1.0],
        ticklen: 2,
        ticks: "outside",
        tickwidth: 0,
        title: { text: "Player" },
        zeroline: true,
        zerolinecolor: colorMode.value === "dark" ? "white" : "black",
        zerolinewidth: 2,
      },
    },
    { responsive: true },
  );

  Plotly.newPlot(
    "aefef167-842a-42f4-b1ed-abd0ebf5f012",
    [
      {
        alignmentgroup: "True",
        cliponaxis: false,
        hovertemplate:
          "Fill Cancelled %=%{x}\u003cbr\u003ePlayer=%{y}\u003cextra\u003e\u003c\u002fextra\u003e",
        legendgroup: "",
        marker: { color: "#636efa", pattern: { shape: "" } },
        name: "",
        offsetgroup: "",
        orientation: "h",
        showlegend: false,
        textangle: 0,
        textposition: "auto",
        texttemplate: "%{x:.2%}",
        x: [
          0.0, 0.25263157894736843, 0.25806451612903225, 0.23529411764705882,
          0.0, 0.0, 0.0, 0.0, 0.2, 0.0, 0.03225806451612903, 0.0,
          0.6666666666666666, 0.3333333333333333, 0.25, 0.0,
          0.30434782608695654, 0.0, 0.3076923076923077, 0.4444444444444444, 0.0,
          0.20833333333333334, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4,
          0.06818181818181818, 0.0, 0.4, 0.0, 0.0, 0.0, 0.4, 0.3333333333333333,
          0.0, 0.25, 0.25, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        ],
        xaxis: "x",
        y: [
          "Levi",
          "Ninmay",
          "TheerapakG",
          "Ane",
          "chinatsu",
          "Ayu",
          "Zephyr",
          "Zephyr Alt",
          "sagi",
          "Berryy",
          "Cycada",
          "koomee",
          "Marina",
          "\u535a\u9e97\u970a\u5922 (Alls)",
          "jayy",
          "sabre",
          "ninmay alt",
          "alex",
          "CQ",
          "CQ (alt)",
          "Waffle",
          "yukari",
          "slay",
          "Carbage",
          "Linkle",
          "clemeycat",
          "orange",
          "lizzie",
          "Yuu",
          "loom",
          "tofeliiiiiiz",
          "Yozora",
          "Kurumi!!",
          "roxas",
          "luna",
          "Suzu",
          "bunch",
          "An!",
          "Kenny (baryons)",
          "DaraDara",
          "Fuego",
          "Sagi alt",
          "shua \u2661",
          "PUBGE",
          "rav",
          "Tiny",
          "Tai \u2727 \u002f\u002f\u002f",
          "woaichixigua",
        ],
        yaxis: "y",
        type: "bar",
      },
    ],
    {
      barmode: "relative",
      font: {
        family: "YurukaStd",
        color: colorMode.value === "dark" ? "white" : "black",
      },
      height: 1600,
      legend: { tracegroupgap: 0 },
      paper_bgcolor: colorMode.value === "dark" ? "black" : "white",
      plot_bgcolor: colorMode.value === "dark" ? "black" : "white",
      template: {
        layout: {
          paper_bgcolor: colorMode.value === "dark" ? "black" : "white",
          plot_bgcolor: colorMode.value === "dark" ? "black" : "white",
          title: { x: 0.05 },
          xaxis: {
            automargin: true,
            gridcolor: colorMode.value === "dark" ? "black" : "white",
            linecolor: colorMode.value === "dark" ? "black" : "white",
            ticks: "",
            title: { standoff: 15 },
            zerolinecolor: colorMode.value === "dark" ? "white" : "black",
            zerolinewidth: 2,
          },
          yaxis: {
            automargin: true,
            gridcolor: colorMode.value === "dark" ? "black" : "white",
            linecolor: colorMode.value === "dark" ? "black" : "white",
            ticks: "",
            title: { standoff: 15 },
            zerolinecolor: colorMode.value === "dark" ? "white" : "black",
            zerolinewidth: 2,
          },
        },
      },
      title: {
        font: { size: 48 },
        text: "Fill % Cancelled By Katsu",
        x: 0.5,
        xanchor: "center",
        y: 0.96,
        yanchor: "middle",
      },
      xaxis: {
        anchor: "y",
        domain: [0.0, 1.0],
        gridcolor: "silver",
        gridwidth: 1,
        showgrid: true,
        title: { text: "Fill Cancelled %" },
        zeroline: true,
        zerolinecolor: colorMode.value === "dark" ? "white" : "black",
        zerolinewidth: 2,
      },
      yaxis: {
        anchor: "x",
        categoryorder: "total ascending",
        domain: [0.0, 1.0],
        ticklen: 2,
        ticks: "outside",
        tickwidth: 0,
        title: { text: "Player" },
        zerolinecolor: colorMode.value === "dark" ? "white" : "black",
        zerolinewidth: 2,
      },
    },
    { responsive: true },
  );

  Plotly.newPlot(
    "40890e67-e735-4bc6-9414-f53a13e22d68",
    [
      {
        alignmentgroup: "True",
        cliponaxis: false,
        hovertemplate:
          "Type=Managed\u003cbr\u003eHours=%{x}\u003cbr\u003ePlayer=%{y}\u003cextra\u003e\u003c\u002fextra\u003e",
        legendgroup: "Managed",
        marker: { color: "deepskyblue", pattern: { shape: "" } },
        name: "Managed",
        offsetgroup: "Managed",
        orientation: "h",
        showlegend: true,
        textangle: 0,
        textposition: "inside",
        texttemplate: "%{x}",
        x: [9, 42, 25, 5, 12],
        xaxis: "x",
        y: ["Levi", "Ninmay", "TheerapakG", "Ane", "sagi"],
        yaxis: "y",
        type: "bar",
      },
      {
        alignmentgroup: "True",
        cliponaxis: false,
        hovertemplate:
          "Type=Managed Cancelled by Katsu\u003cbr\u003eHours=%{x}\u003cbr\u003ePlayer=%{y}\u003cextra\u003e\u003c\u002fextra\u003e",
        legendgroup: "Managed Cancelled by Katsu",
        marker: { color: "darkorange", pattern: { shape: "" } },
        name: "Managed Cancelled by Katsu",
        offsetgroup: "Managed Cancelled",
        orientation: "h",
        showlegend: true,
        textangle: 0,
        textposition: "inside",
        texttemplate: "%{x}",
        x: [0, 17, 2, 10, 6],
        xaxis: "x",
        y: ["Levi", "Ninmay", "TheerapakG", "Ane", "sagi"],
        yaxis: "y",
        type: "bar",
      },
    ],
    {
      barmode: "relative",
      font: {
        family: "YurukaStd",
        color: colorMode.value === "dark" ? "white" : "black",
      },
      height: 955,
      legend: { title: { text: "Type" }, tracegroupgap: 0 },
      paper_bgcolor: colorMode.value === "dark" ? "black" : "white",
      plot_bgcolor: colorMode.value === "dark" ? "black" : "white",
      template: {
        layout: {
          paper_bgcolor: colorMode.value === "dark" ? "black" : "white",
          plot_bgcolor: "#E5ECF6",
          title: { x: 0.05 },
          xaxis: {
            automargin: true,
            gridcolor: colorMode.value === "dark" ? "black" : "white",
            linecolor: colorMode.value === "dark" ? "black" : "white",
            ticks: "",
            title: { standoff: 15 },
            zerolinecolor: colorMode.value === "dark" ? "black" : "white",
            zerolinewidth: 2,
          },
          yaxis: {
            automargin: true,
            gridcolor: colorMode.value === "dark" ? "black" : "white",
            linecolor: colorMode.value === "dark" ? "black" : "white",
            ticks: "",
            title: { standoff: 15 },
            zerolinecolor: colorMode.value === "dark" ? "black" : "white",
            zerolinewidth: 2,
          },
        },
      },
      title: {
        font: { size: 48 },
        text: "Managed",
        x: 0.5,
        xanchor: "center",
        y: 0.96,
        yanchor: "middle",
      },
      xaxis: {
        anchor: "y",
        domain: [0.0, 1.0],
        gridcolor: "silver",
        gridwidth: 1,
        showgrid: true,
        title: { text: "Hours" },
        zeroline: true,
        zerolinecolor: colorMode.value === "dark" ? "white" : "black",
        zerolinewidth: 2,
      },
      yaxis: {
        anchor: "x",
        categoryorder: "total ascending",
        domain: [0.0, 1.0],
        ticklen: 2,
        ticks: "outside",
        tickwidth: 0,
        title: { text: "Player" },
        zeroline: true,
        zerolinecolor: colorMode.value === "dark" ? "white" : "black",
        zerolinewidth: 2,
      },
    },
    { responsive: true },
  );

  Plotly.newPlot(
    "6fa39b08-48a1-4732-99ca-b5a33d3e8ba7",
    [
      {
        alignmentgroup: "True",
        cliponaxis: false,
        hovertemplate:
          "Managed Cancelled %=%{x}\u003cbr\u003ePlayer=%{y}\u003cextra\u003e\u003c\u002fextra\u003e",
        legendgroup: "",
        marker: { color: "#636efa", pattern: { shape: "" } },
        name: "",
        offsetgroup: "",
        orientation: "h",
        showlegend: false,
        textangle: 0,
        textposition: "auto",
        texttemplate: "%{x:.2%}",
        x: [
          0.0, 0.288135593220339, 0.07407407407407407, 0.6666666666666666,
          0.3333333333333333,
        ],
        xaxis: "x",
        y: ["Levi", "Ninmay", "TheerapakG", "Ane", "sagi"],
        yaxis: "y",
        type: "bar",
      },
    ],
    {
      barmode: "relative",
      font: {
        family: "YurukaStd",
        color: colorMode.value === "dark" ? "white" : "black",
      },
      height: 955,
      legend: { tracegroupgap: 0 },
      paper_bgcolor: colorMode.value === "dark" ? "black" : "white",
      plot_bgcolor: colorMode.value === "dark" ? "black" : "white",
      template: {
        layout: {
          paper_bgcolor: colorMode.value === "dark" ? "black" : "white",
          plot_bgcolor: colorMode.value === "dark" ? "black" : "white",
          title: { x: 0.05 },
          xaxis: {
            automargin: true,
            gridcolor: colorMode.value === "dark" ? "black" : "white",
            linecolor: colorMode.value === "dark" ? "black" : "white",
            ticks: "",
            title: { standoff: 15 },
            zerolinecolor: colorMode.value === "dark" ? "black" : "white",
            zerolinewidth: 2,
          },
          yaxis: {
            automargin: true,
            gridcolor: colorMode.value === "dark" ? "black" : "white",
            linecolor: colorMode.value === "dark" ? "black" : "white",
            ticks: "",
            title: { standoff: 15 },
            zerolinecolor: colorMode.value === "dark" ? "black" : "white",
            zerolinewidth: 2,
          },
        },
      },
      title: {
        font: { size: 48 },
        text: "Managed % Cancelled By Katsu",
        x: 0.5,
        xanchor: "center",
        y: 0.96,
        yanchor: "middle",
      },
      xaxis: {
        anchor: "y",
        domain: [0.0, 1.0],
        gridcolor: "silver",
        gridwidth: 1,
        showgrid: true,
        title: { text: "Managed Cancelled %" },
        zeroline: true,
        zerolinecolor: colorMode.value === "dark" ? "white" : "black",
        zerolinewidth: 2,
      },
      yaxis: {
        anchor: "x",
        categoryorder: "total ascending",
        domain: [0.0, 1.0],
        ticklen: 2,
        ticks: "outside",
        tickwidth: 0,
        title: { text: "Player" },
        zerolinecolor: colorMode.value === "dark" ? "white" : "black",
        zerolinewidth: 2,
      },
    },
    { responsive: true },
  );
};

onMounted(async () => {
  const colorMode = useColorMode();

  plotCharts();
  watch(colorMode, plotCharts);
});
</script>

<template>
  <UContainer
    class="thin-scrollbars relative flex flex-col place-content-center place-items-center gap-y-2 overflow-x-auto pt-0 md:pt-16 2xl:pt-0"
  >
    <div
      id="1ece9e8b-b3de-4c21-a2ca-79603884e11e"
      class="plotly-graph-div"
      style="height: 1600px; width: 100%"
    ></div>
    <div
      id="aefef167-842a-42f4-b1ed-abd0ebf5f012"
      class="plotly-graph-div"
      style="height: 1600px; width: 100%"
    ></div>
    <div
      id="40890e67-e735-4bc6-9414-f53a13e22d68"
      class="plotly-graph-div"
      style="height: 955px; width: 100%"
    ></div>
    <div
      id="6fa39b08-48a1-4732-99ca-b5a33d3e8ba7"
      class="plotly-graph-div"
      style="height: 955px; width: 100%"
    ></div>
  </UContainer>
</template>
