apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valkey-claim
  labels:
    app: valkey
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
