apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: theerapakg-moe-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - theerapakg.moe
      secretName: theerapakg-moe-tls
  rules:
    - host: theerapakg.moe
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: theerapakg-moe-web-service
                port:
                  number: 80
