apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: theerapakg-moe-web-secret
    envs:
      - .env.secret
configMapGenerator:
generatorOptions:
  disableNameSuffixHash: true
resources:
