apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: "supabase/postgres:15.1.1.80"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres-svc
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: postgres-svc
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service-external
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5432
      targetPort: postgres-svc
      nodePort: 31000
  selector:
    app: postgres
