apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: postgres-secret
    envs:
      - .env.secret
configMapGenerator:
resources:
  - volume.yaml
  - claim.yaml
  - deployment.yaml
