name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup node.js/yarn
      uses: actions/setup-node@v3
      with:
        node-version: "16"
        cache: 'yarn'
        
    - name: Install Dependencies
      run: yarn install
    
    - name: Run Lint
      run: yarn eslint .

  typecheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup node.js/yarn
      uses: actions/setup-node@v3
      with:
        node-version: "16"
        cache: 'yarn'
        
    - name: Install Dependencies
      run: yarn install
    
    - name: Run Typecheck
      run: yarn nuxi typecheck

  build:
    needs: [lint, typecheck]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup node.js/yarn
      uses: actions/setup-node@v3
      with:
        node-version: "16"
        cache: 'yarn'
        
    - name: Install Dependencies
      run: yarn install
    
    - name: Run Build
      run: yarn nuxi build

    - name: Tar Build
      run: tar -czvf build.tar.gz .output

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build.tar.gz
