name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/setup.yml

    steps:
    - name: Run lint
      run: yarn eslint .

  typecheck:
    uses: ./.github/workflows/setup.yml

    steps:
    - name: Run typecheck
      run: yarn nuxi typecheck
